name: Build

on: [push, pull_request]

jobs:
  build:
    name: Source Distribution and Wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - uses: actions/upload-artifact@v4
        with:
          path: dist
